### ISSUE TITLE
parameters.yml needs default value besides 'null' for several parameters

### ISSUE THREAD

**Issue by sonjahohlfeld** [molbiodiv/fennec#107]
If you set up the Docker environment for Fennec you need to set values for ```github_client_id, github_client_secret, google_client_id``` and  ```google_client_secret```. Otherwise these values are setted with ```null```. But in this case it is not possible to do a ```composer install```.
Therefore it would be nice if the default value is not ```null```.

**Comment by iimog** [comment]
implemented and merged into develop, will be part of 1.0.0
