### ISSUE TITLE
Create demo user account 

### ISSUE THREAD

**Issue by sonjahohlfeld** [molbiodiv/fennec#109]
FENNEC should provide a demo user account for test purposes

**Comment by iimog** [comment]
This feature is no longer required as it is straightforward to create a user account and example projects are described in detail in the manual.
Two alternative ideas exist:
 - if no user is logged in, only demo projects are visible (read only) with a banner notice
 - beside the project upload button there is an option to load a demo project

Those are ideas for the future.
