### ISSUE TITLE
Discussion about existing webuser table

### ISSUE THREAD

**Issue by sonjahohlfeld** [molbiodiv/fennec#116]
At the moment the old webuser table contains "special" users like EPPO, WorldCropsDatabase, EOL, etc. But the webuser table has no more relations to other tables e.g webuser_data and trait_numerical_entry. The new table fennec_user references those tables. But the updating of the database schema results in error messages because some traits in trait_categorical_entry have a webuser_id (= fennec_user_id). At that time there are no fennec_users which results in the following error messages: 

```
[Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException]             
  An exception occurred while executing 'ALTER TABLE trait_numerical_entry AD  
  D CONSTRAINT FK_1AE414EE49279951 FOREIGN KEY (webuser_id) REFERENCES "fenne  
  c_user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE':                            
  SQLSTATE[23503]: Foreign key violation: 7 ERROR:  insert or update on table  
   "trait_numerical_entry" violates foreign key constraint "fk_1ae414ee492799  
  51"                                                                          
  DETAIL:  Key (webuser_id)=(1) is not present in table "fennec_user".  
```

We should discuss if default users for EPPO, EOL, WorldCropsDatabase etc. are setted or if there is another suitable solution.

**Comment by phryneas** [comment]
These users should probably just be created as special user that are always present in the database.

For that case, the installation progress for starting with an empty database would need an additional step: either applying fixtures, or migrations which would create the entities. I would lean towards fixtures.

Also, the example fennec.sql.xz dataset would need to contain these users in the future.

**Comment by sonjahohlfeld** [comment]
If we start with an empty database it contains neither users nor traits. So the absence of special users should be no problem. For the other case we create a new version of the database which fits the new user management.
