### ISSUE TITLE
The client secret is a leaked in the blob file 

### ISSUE THREAD

**Issue by yevh** [molbiodiv/fennec#216]
Hi there,

I found that client secret is a leaked in the parameters.yml:

https://github.com/molbiodiv/fennec/blob/master/docker/fennec/parameters.yml

Be secure!

**Comment by iimog** [comment]
Thanks a lot @yevh 
I made sure that this secret is not actually used by any of my running instances and replaced the value with a dummy value to prevent people from using this value.
Thanks again for reporting!
