### ISSUE TITLE
Create a contact page

### ISSUE THREAD

**Issue by sonjahohlfeld** [molbiodiv/fennec#43]

**Comment by iimog** [comment]
Looking at this article (german) I'd say that we do not necessarily need it:
https://www.it-recht-kanzlei.de/Thema/impressum-tmg.html?#sect_1

citing the article from above (2017-04-04):
> Nach § 5 TMG trifft die Impressumspflicht alle Diensteanbieter, die geschäftsmäßige, in der Regel gegen Entgelt angebotene, Telemedien bereithalten.

Still it can't hurt to provide some means of creating a contact page.
The contact page has to be configurable as it has to hold the content from the instance admin.

**Comment by iimog** [comment]
Done
